export type StockDataType = {
  month: string;
  year: string;
  value: number;
};

export const stockData: StockDataType[] = [
  { month: 'January', year: '2019', value: 7 },
  { month: 'February', year: '2019', value: -2 },
  { month: 'March', year: '2019', value: 10 },
  { month: 'April', year: '2019', value: -4 },
  { month: 'May', year: '2019', value: 8 },
  { month: 'June', year: '2019', value: 1 },
  { month: 'July', year: '2019', value: -9 },
  { month: 'August', year: '2019', value: -8 },
  { month: 'September', year: '2019', value: 2 },
  { month: 'October', year: '2019', value: 5 },
  { month: 'November', year: '2019', value: -7 },
  { month: 'December', year: '2019', value: 3 },
  { month: 'January', year: '2020', value: -1 },
  { month: 'February', year: '2020', value: -6 },
  { month: 'March', year: '2020', value: 9 },
  { month: 'April', year: '2020', value: -5 },
  { month: 'May', year: '2020', value: -10 },
  { month: 'June', year: '2020', value: 4 },
  { month: 'July', year: '2020', value: 6 },
  { month: 'August', year: '2020', value: -3 },
  { month: 'September', year: '2020', value: 10 },
  { month: 'October', year: '2020', value: -8 },
  { month: 'November', year: '2020', value: 7 },
  { month: 'December', year: '2020', value: -9 },
  { month: 'January', year: '2021', value: 2 },
  { month: 'February', year: '2021', value: 8 },
  { month: 'March', year: '2021', value: -7 },
  { month: 'April', year: '2021', value: 3 },
  { month: 'May', year: '2021', value: -4 },
  { month: 'June', year: '2021', value: -1 },
  { month: 'July', year: '2021', value: 6 },
  { month: 'August', year: '2021', value: 4 },
  { month: 'September', year: '2021', value: -3 },
  { month: 'October', year: '2021', value: 9 },
  { month: 'November', year: '2021', value: -10 },
  { month: 'December', year: '2021', value: 5 },
  { month: 'January', year: '2022', value: 7 },
  { month: 'February', year: '2022', value: -6 },
  { month: 'March', year: '2022', value: 4 },
  { month: 'April', year: '2022', value: 10 },
  { month: 'May', year: '2022', value: -8 },
  { month: 'June', year: '2022', value: 1 },
  { month: 'July', year: '2022', value: -5 },
  { month: 'August', year: '2022', value: 3 },
  { month: 'September', year: '2022', value: -2 },
  { month: 'October', year: '2022', value: 5 },
  { month: 'November', year: '2022', value: -9 },
  { month: 'December', year: '2022', value: -4 },
  { month: 'January', year: '2023', value: 8 },
  { month: 'February', year: '2023', value: -1 },
  { month: 'March', year: '2023', value: 6 },
  { month: 'April', year: '2023', value: -10 },
  { month: 'May', year: '2023', value: 4 },
  { month: 'June', year: '2023', value: 2 },
  { month: 'July', year: '2023', value: -7 },
  { month: 'August', year: '2023', value: -3 },
  { month: 'September', year: '2023', value: 9 },
  { month: 'October', year: '2023', value: 1 },
  { month: 'November', year: '2023', value: -6 },
  { month: 'December', year: '2023', value: 7 },
  // { month: 'January', year: '2024', value: 1 },
];

export const months = Array.from(new Set(stockData.map((d) => d.month)));
export const years = Array.from(new Set(stockData.map((d) => d.year)));
